
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: registry.local/docker-registry/pooi-workflow
        name: pooi-workflow
        resources:
          limits:
            memory: 256Mi
            cpu: 50m
